spring.application.name=bellefood-backend
server.port=8083

firebase.database.url=https://bellefood-02-default-rtdb.firebaseio.com

logging.level.org.springframework=INFO
logging.level.com.bellefood=DEBUG